name: vid_loop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.1
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  get: ^4.7.2
#  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
#    - assets/icons/
    - .env

#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/app_icon.png"